on: [push, pull_request, create, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: config/
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-v2-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Initialize workspace (west init)
        run: west init -l config
      - name: Update modules (west update)
        run: west update
      - name: Export zephyr CMake package (west zephyr-export)
        run: west zephyr-export
      - name: List modules (west list)
        run: west list
      - name: Build (west build)
        run: west build -s zmk/app -b zaphod -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Zaphod .config
        if: ${{ always() }}
        run: cat -n build/zephyr/.config
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 zaphod.uf2
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: zaphod.uf2
